services:

  # Reverse proxy / entry point
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - gateway
      - service-checker
      - status-page
    networks:
      - transcendence-net

  # Frontend
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - transcendence-net

  # Gateway API
  gateway:
    container_name: gateway
    build: ./backend/gateway
    ports:
      - "3005:3005"
    networks:
      - transcendence-net

  # Auth service
  auth-service:
    container_name: auth-service
    build: ./backend/auth-service
    ports:
      - "3001:3000"
    networks:
      - transcendence-net

  # User service
  user-service:
    container_name: user-service
    build: ./backend/user-service
    ports:
      - "3002:3000"
    networks:
      - transcendence-net

  # Game service
  game-service:
    container_name: game-service
    build: ./backend/game-service
    ports:
      - "3003:3000"
    networks:
      - transcendence-net
  

  game-standalone:
    container_name: game-standalone
    build: ./backend/game-standalone
    ports:
      - "3010:3010"
    networks:
      - transcendence-net

  # Health system
  service-checker:
    container_name: service-checker
    build: ./healthcheck/service-checker
    ports:
      - "4000:4000"
    networks:
      - transcendence-net

  status-page:
    container_name: status-page
    build: ./healthcheck/status-page
    ports:
      - "3007:3000"
    networks:
      - transcendence-net

  # Database
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - transcendence-net
    depends_on:
      - auth-service
      - user-service
      - game-service
      - gateway

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3006:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=superadmin
      - GF_SECURITY_ADMIN_PASSWORD=superpassword
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

    networks:
      - transcendence-net
    depends_on:
      - prometheus

# Custom network for all services
networks:
  transcendence-net:
    driver: bridge

# Persistent volume for database
volumes:
  postgres_data:
  grafana_data: